version: '3.4'
volumes:
  mariadb:
    name: mariadb.volume
  storage:
    name: storage.volume

services:
  db:
    image: db.image
    container_name: db.local
    restart: always
    build:
      dockerfile: db/Dockerfile
      context: .
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "agorakit"
      MYSQL_USER: "agorakit"
      MYSQL_PASSWORD: "p@ssw0rd"
    #entrypoint: ["mysqld_safe", "--skip-grant-tables", "--skip-networking"] # in case of DB maintenance => docker exec -it db.local mariadb -uroot
    volumes:
      - mariadb:/var/lib/mysql
      - storage:/tmp/storage

  agorakit:
    container_name: agorakit.local
    image: agorakit.image
    restart: always
#    environment:
#      S3_BACKUP_BUCKET_NAME: "iqmgjxzvttutcmbucab"
    build:
      dockerfile: agorakit/Dockerfile
      context: .
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /home/centos/.megaCmd:/root/.megaCmd
      - ./aws:/root/.aws
      - storage:/opt/agorakit/storage
      - ./agorakit/CommentController.php:/opt/agorakit/app/Http/Controllers/CommentController.php
      - ./agorakit/comment.blade.php:/opt/agorakit/resources/views/comments/comment.blade.php
      - ./agorakit/presentation.blade.php:/opt/agorakit/resources/views/dashboard/presentation.blade.php
      - ./agorakit/groups.blade.php:/opt/agorakit/resources/views/dashboard/groups.blade.php
      - ./agorakit/fr.json:/opt/agorakit/resources/lang/fr.json
      - ./agorakit/fr:/opt/agorakit/resources/lang/fr
      - ./agorakit/.env:/opt/agorakit/.env
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
