version: '3.4'
volumes:
  mariadb:
    name: mariadb.volume
  storage:
    name: storage.volume

services:
  db:
    image: mariadb
    container_name: db.local
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "agorakit"
      MYSQL_USER: "agorakit"
      MYSQL_PASSWORD: "p@ssw0rd"
    #entrypoint: ["mysqld_safe", "--skip-grant-tables", "--skip-networking"] # in case of DB maintenance => docker exec -it db.local mariadb -uroot
    volumes:
      - mariadb:/var/lib/mysql

  agorakit:
    container_name: agorakit.local
    image: agorakit.image
    build:
      dockerfile: agorakit/Dockerfile
      context: .
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - storage:/opt/agorakit/storage
      - ./agorakit/fr.json:/opt/agorakit/resources/lang/fr.json
      - ./agorakit/fr:/opt/agorakit/resources/lang/fr
      - ./agorakit/.env:/opt/agorakit/.env
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
